### ISSUE TITLE
Can't scroll page when the mouse is over the navBar

### ISSUE THREAD

**Issue by KostyalBalint** [berenteb/bkk-nearby-departures#23]
Scrolling work's just fine when on the cursor is over the main page, but when I try to scroll if the cursor is over the title it's not scrolling. 
Tested in Chrome and Safari

**Comment by berenteb** [comment]
The titleBar element is not a child of the content element, which is scrollable. This layout prevents the site from scrolling when the settings panel is visible. The app element takes up the whole screen and the overflow of the content element is scrollable.
